### PR TITLE
Translated strings in es.json

### PR DESCRIPTION
**Pull request by natastro**
Referencing #405 

Translated https://github.com/ubilabs/esa-climate-from-space/blob/develop/i18n/es.json 

@pmast @pwambach 

> "storiesSelected": "{numberSelected, number} {numberSelected, plural, one {Story} other {Stories}} selected"

You'll see this is now '"storiesSelected": "{numberSelected, number} {numberSelected, plural, one {**Historia**} other {**Historias**}} **seleccionada(s)**"'
If you need me to change this, please let me know! Thank you for letting me assist and if you need anything else just let me know!

### CODE REVIEW

**Comment by pmast** [comment]
Hi @natastro thanks a lot! How did you happen to end up here?
Have you been searching Github for translation tasks?

**Comment by natastro** [comment]
Hi @pmast ! Yes - I usually look around through the issues on GitHub and see if I can help anyone with Spanish translations as it's something I enjoy doing. 😄

**Comment by natastro** [comment]
Hi @pwambach ! Sorry about that, I went ahead and reverted it. Please let me know if you need anything else. Have a good one!

**Comment by pwambach** [comment]
Perfect, thanks again for your support!

**Pull request merged**
