### PR TITLE
feat(layer-info): content updates

### PR DESCRIPTION
**Pull request by pmast**
Might be controversial: added HTML support for React markdown in the layers-info to support the extended legend for landcover:

image

### CODE REVIEW

**Comment by mrMetalWood** [comment]
Not sure about the HTML support and its implications. Lets see what @pwambach says :) Fine with me

**Review by mrMetalWood — APPROVED** [review]

**Comment by pwambach** [comment]
Actually I would have preferred to not enable html injects because it's always a security issue to insert html from a remote server. In our case it's not user generated so it "should" be ok, but you never know...

**Comment by pmast** [comment]
I can also try and work with an image instead. I will give it a try later.

**Comment by pwambach** [comment]
But we would need one image per language :(

**Comment by pmast** [comment]
True…

**Comment by pmast** [comment]
Is there an option for screenshotting HTML elements with transparent background?

**Pull request merged**
