### PR TITLE
feat(stories): add stories 42 and 43

### PR DESCRIPTION
**Pull request by Immo-Be**
- add new stories
for #1340

@pmast I've adapted the `stories-[language].json` and added new `story-[number].json` ➡︎ I was wondering about the `videoId` Parameter. All other stories seem to have it, I did not find any information about them in the .csv

### CODE REVIEW

**Comment by pmast** [comment]
The `videoId` fields refers to a youtube ID and is an alternative way of defining videos.
Either on of the two has to be defined: `videoId` or `videoSrc`.  `videoSrc` takes precedence over `videoId`, favouring HTML5 videos above youtube videos.

**Review by pmast — CHANGES_REQUESTED** [review]
Sorry, left comments on the wrong level of this PR: https://github.com/ubilabs/esa-climate-from-space/pull/1344#issuecomment-1932375480

**Comment by Immo-Be** [comment]
> Looks good!
> 
> Please use he translated story titles from within the spreadsheet as the story title in the `stories-[language].json` files. The content for the `story-[number].json` files can be set with the story mapper once the index file is uploaded.

I was wondering about that too, but I don't see any translations for the titles (or description) in the spreadsheet. It's always English 🧐

**Comment by pmast** [comment]
> > Looks good!
> > Please use he translated story titles from within the spreadsheet as the story title in the `stories-[language].json` files. The content for the `story-[number].json` files can be set with the story mapper once the index file is uploaded.
> 
> I was wondering about that too, but I don't see any translations for the titles (or description) in the spreadsheet. It's always English 🧐

OK, well then… 😃

**Review by pmast — APPROVED** [review]

**Pull request merged**
